### ISSUE TITLE
Windows line spaces

### ISSUE THREAD

**Issue by stormymauldin** [r2labs/QuARC#1]
After cloning a repo in Windows, and entering the Vagrant build environment, `source ./configure` broke on an unexpected '\r'. This can be fixed by running dos2unix on the files from inside Vagrant. 

Discuss the best place to hook this conversion in to the build process.

**Comment by hershal** [comment]
Will test

**Comment by hershal** [comment]
Seems to work for me (though I'm using Cygwin's git). Make sure your git client isn't changing the line endings on you, i.e. make sure it's set to Unix LF.

**Comment by hershal** [comment]
ARB'd (Action Required By) Stormy.

**Comment by EricCrosson** [comment]
Seems to me a fix that is once per-repo and not once per-client would be better.
Have you experience with .gitattribute files? I have none, but this looks promising.
http://stackoverflow.com/a/10855862

If we were to convert all of our files to LF only, that would look like a simple 

```
/**/* text eol=lf
```

Nixing the CR entirely is the goal, right?

Stormy: to change your client's handling of line endings, you can go to the gear icon (in the upper right corner) > Repository settings ... > Line endings and attributes.

**Comment by johnathankyle** [comment]
> Stormy: to change your client's handling of line endings, you can go to the gear icon (in the upper right > corner) > Repository settings ... > Line endings and attributes.

Where exactly are you doing this?

**Comment by EricCrosson** [comment]
In his git client, i.e. the client downloaded from https://windows.github.com/

**Comment by hershal** [comment]
I've added the .gitattributes file. Stormy, you may have to do a `git update-index --refresh` after you pull the changes to see the results.

**Comment by stormymauldin** [comment]
Hey, just checked my email, will do this as soon as I get home!

**Comment by EricCrosson** [comment]
Nice, hopefully this will also allow our group to edit from windows and immediately build from the repo. One interruption might appear if the .gitattributes doesn't kick in until a commit is triggered -- then we may still need to integrate a dos2unix call from inside the build() function. So long as the ./configure script sources appropriately during the beginning of the session (assuming a clean repo, this shouldn't be a problem) the addition to build() would negate this line ending problem forever. 

Let's see how it works for Stormy.

**Comment by stormymauldin** [comment]
I just tried and I am able to run vagrant, pull, and sync normally, so I am not seeing any issues here. Was this problem something we added on here the other day?

**Comment by EricCrosson** [comment]
Will you edit one of the building src files from windows (add a new line or something), save it and try to build and run the tests again?

**Comment by stormymauldin** [comment]
ok now im getting an permission error upon my attempt to push changes... It says I don't have access to the repo. I was able to change line ending settings though.

**Comment by stormymauldin** [comment]
forgive me if there is a gap in my responses, i am pretty tired and may fall asleep

**Comment by hershal** [comment]
Check remotes (`git remote -v`). If you're using https://github.com/r2labs/QuARC as your remote URL, then you must change it:
`git remote set-url origin ssh://git@github.com/r2labs/QuARC`.

Does that help?

**Comment by stormymauldin** [comment]
Sorry, I fell asleep, but will try this when I get home from work!

**Comment by EricCrosson** [comment]
> I was able to change line ending settings though.

You only have to push this simple change if you really want to. 
Question, you were able to change the line endings from where? Were you required to do it manually after your edit from windows or did it "just work"?

**Comment by stormymauldin** [comment]
I opened up a file and edited straight from there

**Comment by stormymauldin** [comment]
This is the error I am getting. I made sure the URL was correct, but to no avail.
![error](https://cloud.githubusercontent.com/assets/12601012/8584706/0df6d5de-259f-11e5-9734-1872267a68e3.PNG)

**Comment by hershal** [comment]
You need to accept the invitation to join the r2labs group. See if you have any unread GitHub notifications.

**Comment by stormymauldin** [comment]
I don't have any notifications in my inbox, and it even says that I am a member of r2labs. Any other ideas?

**Comment by stormymauldin** [comment]
I'M IN! Thanks man!
